In [2]:
import pandas as pd

In [8]:
data = pd.read_csv("D:/计算机大三上/大数据分析实践/project/CN-Reanalysis201301/201301/CN-Reanalysis-daily-2013010100.csv")
data['data'] = '13-1-1'
for month in range(1,13):
    for day in range(32):
        try:
            with open("D:/计算机大三上/大数据分析实践/project/CN-Reanalysis201301/201301/CN-Reanalysis-daily-201301{}00.csv".format(day),'r',encoding='utf-8') as file:
                temp_data=pd.read_csv(file)
                temp_data['data'] = '13-{}-{}'.format(month,day)
        except FileNotFoundError:
            continue
        data = pd.concat([data,temp_data])

In [13]:
data

,PM2.5(微克每立方米),PM10(微克每立方米),SO2(微克每立方米),NO2(微克每立方米),CO(毫克每立方米),O3(微克每立方米),U(m/s),V(m/s),TEMP(K),RH(%),PSFC(Pa),lat,lon,data
0,20.21,23.56,8.65,4.58,0.29,63.44,-2.48,-2.31,291.54,68.14,100350.11,18.34,109.25,13-1-1
1,20.41,23.96,9.28,5.24,0.29,62.53,-3.43,-3.21,291.96,67.41,100546.63,18.34,109.38,13-1-1
2,21.17,24.78,10.07,5.47,0.30,62.24,-3.43,-4.72,291.37,69.59,100428.13,18.33,109.52,13-1-1
3,22.24,26.04,10.36,5.28,0.30,63.58,-2.92,-5.32,290.74,72.94,100569.27,18.33,109.66,13-1-1
4,19.68,22.34,7.62,3.58,0.29,66.21,-2.51,-3.13,291.67,65.97,101620.34,18.49,108.83,13-1-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42244,1.93,2.08,2.67,0.98,0.21,41.14,6.20,-0.67,244.52,71.47,99430.13,53.18,125.08,13-12-31
42245,1.65,1.81,1.97,0.74,0.21,41.83,4.77,-0.27,243.42,71.17,97591.93,53.51,123.24,13-12-31
42246,1.68,1.84,2.28,0.80,0.21,41.56,5.54,-1.39,243.91,70.57,97713.55,53.49,123.45,13-12-31
42247,1.69,1.85,2.45,0.85,0.21,41.59,5.24,-2.13,244.23,70.46,98297.62,53.47,123.66,13-12-31
42248,1.68,1.85,2.59,0.92,0.21,42.07,4.53,-1.80,243.74,70.65,98812.94,53.44,123.87,13-12-31

In [12]:
data.to_csv('13_with_time.csv')